spring:
  application:
    name: gateway-admin-organizer
  redis:  # Thêm cấu hình Redis
    host: localhost
    port: 6379
  cloud:
    gateway:
      routes:
        - id: identity-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/organizer/register, /api/admin/users/**, /api/organizer/**, /api/auth/**
        - id: event-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/admin/events/**, /api/organizer/events/**
        - id: ticket-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/admin/tickets/**, /api/organizer/tickets/**
      default-filters:
        - AuthFilter
server:
  port: 8085
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.example.gatewayadminorganizer: DEBUG