spring:
  application:
    name: gateway-app
  data:
    redis:
      host: localhost
      port: 6379
  cloud:
    gateway:
      routes:
        - id: identity-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/register, /api/auth/**, /api/users/**
        - id: event-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/events/public/**, /api/events/**, /ws/**, /ws-native/**
          filters:
            - name: ModifyResponseBody
              args:
                inClass: java.lang.String
                outClass: java.lang.String
                rewriteFunction: "#{@cacheRewriteFunction}"
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1000   # Tăng lên 1000 yêu cầu/phút
                redis-rate-limiter.burstCapacity: 2000   # Tăng lên 2000 yêu cầu đột biến
                key-resolver: "#{@remoteAddrKeyResolver}"
        - id: ticket-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/tickets/**, /api/queue/**
        - id: payment-service
          uri: http://localhost:8086
          predicates:
            - Path=/api/payments/**
      default-filters:
        - AuthFilter
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders:
              - "*"
            allowCredentials: true
            maxAge: 3600
server:
  tomcat:
    threads:
      max: 500
      min-spare: 50
  port: 8080
  http2:
    enabled: true                               # Bật HTTP/2
identity:
  service:
    url: http://localhost:8081
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.example.gatewayapp: DEBUG