spring:
  application:
    name: gateway-app
  cloud:
    gateway:
      routes:
        - id: identity-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/register, /api/auth/login/**, /api/auth/forgot-password/**, /api/auth/verify-code/**, /api/auth/reset-password/**, /api/users/**, /api/users/profile/**
        - id: event-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/events/**
        - id: ticket-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/tickets/**
      default-filters:
        - AuthFilter
server:
  port: 8080
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.example.gatewayapp: DEBUG