spring:
  application:
    name: gateway-app
  redis: # Thêm cấu hình Redis
      host: localhost
      port: 6379
  cloud:
    gateway:
      routes:
        - id: identity-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/register, /api/auth/**, /api/users/**
        - id: event-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/events/**
        - id: ticket-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/tickets/**
      default-filters:
        - AuthFilter
server:
  port: 8080
identity:
  service:
    url: http://localhost:8081
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.example.gatewayapp: DEBUG